# Generated by Django 5.2.11 on 2026-02-09 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Galeria de trabajos', max_length=120)),
                ('subtitle', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='GalleryPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('before_image', models.ImageField(upload_to='gallery')),
                ('after_image', models.ImageField(blank=True, upload_to='gallery')),
                ('caption', models.CharField(blank=True, max_length=120)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='pages.gallerypage')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
