# Generated by Django 5.2.11 on 2026-02-09 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_contactpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactpage',
            name='map_embed_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
