# Generated by Django 5.2.11 on 2026-02-09 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_alter_contactpage_map_embed_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='PolicyPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Politicas del salon', max_length=120)),
                ('cancellation', models.TextField(blank=True)),
                ('lateness', models.TextField(blank=True)),
                ('before_after', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
